thread 'main' panicked at 'first', $DIR/double_panic.rs:LL:CC
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'second', $DIR/double_panic.rs:LL:CC
stack backtrace:
   0: std::backtrace_rs::backtrace::miri::trace_unsynchronized
 at rustc_src/src/../../backtrace/src/backtrace/miri.rs:LL:CC
   1: std::backtrace_rs::backtrace::miri::trace
 at rustc_src/src/../../backtrace/src/backtrace/miri.rs:LL:CC
   2: std::backtrace_rs::backtrace::trace_unsynchronized
 at rustc_src/src/../../backtrace/src/backtrace/mod.rs:LL:CC
   3: std::sys_common::backtrace::_print_fmt
 at rustc_src/src/sys_common/backtrace.rs:LL:CC
   4: <std::sys_common::backtrace::_print::DisplayBacktrace as std::fmt::Display>::fmt
 at rustc_src/src/sys_common/backtrace.rs:LL:CC
   5: std::fmt::write
 at rustc_src/src/fmt/mod.rs:LL:CC
   6: <std::sys::PLATFORM::stdio::Stderr as std::io::Write>::write_fmt
 at rustc_src/src/io/mod.rs:LL:CC
   7: std::sys_common::backtrace::_print
 at rustc_src/src/sys_common/backtrace.rs:LL:CC
   8: std::sys_common::backtrace::print
 at rustc_src/src/sys_common/backtrace.rs:LL:CC
   9: std::panicking::default_hook::{closure#1}
 at rustc_src/src/panicking.rs:LL:CC
  10: std::panicking::default_hook
 at rustc_src/src/panicking.rs:LL:CC
  11: std::panicking::rust_panic_with_hook
 at rustc_src/src/panicking.rs:LL:CC
  12: std::rt::begin_panic::{closure#0}
 at rustc_src/src/panicking.rs:LL:CC
  13: std::sys_common::backtrace::__rust_end_short_backtrace
 at rustc_src/src/sys_common/backtrace.rs:LL:CC
  14: std::rt::begin_panic
 at rustc_src/src/panicking.rs:LL:CC
  15: <Foo as std::ops::Drop>::drop
 at $DIR/double_panic.rs:LL:CC
  16: std::ptr::drop_in_place - shim(Some(Foo))
 at rustc_src/src/ptr/mod.rs:LL:CC
  17: main
 at $DIR/double_panic.rs:LL:CC
  18: <fn() as std::ops::FnOnce<()>>::call_once - shim(fn())
 at rustc_src/src/ops/function.rs:LL:CC
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
 at rustc_src/src/sys_common/backtrace.rs:LL:CC
  20: std::rt::lang_start::{closure#0}
 at rustc_src/src/rt.rs:LL:CC
  21: std::ops::function::impls::call_once
 at rustc_src/src/ops/function.rs:LL:CC
  22: std::panicking::r#try::do_call
 at rustc_src/src/panicking.rs:LL:CC
  23: std::panicking::r#try
 at rustc_src/src/panicking.rs:LL:CC
  24: std::panic::catch_unwind
 at rustc_src/src/panic.rs:LL:CC
  25: std::rt::lang_start_internal::{closure#2}
 at rustc_src/src/rt.rs:LL:CC
  26: std::panicking::r#try::do_call
 at rustc_src/src/panicking.rs:LL:CC
  27: std::panicking::r#try
 at rustc_src/src/panicking.rs:LL:CC
  28: std::panic::catch_unwind
 at rustc_src/src/panic.rs:LL:CC
  29: std::rt::lang_start_internal
 at rustc_src/src/rt.rs:LL:CC
  30: std::rt::lang_start
 at rustc_src/src/rt.rs:LL:CC
thread panicked while panicking. aborting.
error: abnormal termination: the program aborted execution
   |
   = note: inside `std::sys::PLATFORM::abort_internal` at rustc_src/src/sys/PLATFORM/mod.rs:LL:CC
   = note: inside `std::panicking::rust_panic_with_hook` at rustc_src/src/panicking.rs:LL:CC
   = note: inside closure at rustc_src/src/panicking.rs:LL:CC
   = note: inside `std::sys_common::backtrace::__rust_end_short_backtrace::<[closure@std::rt::begin_panic<&str>::{closure#0}], !>` at rustc_src/src/sys_common/backtrace.rs:LL:CC
   = note: inside `std::rt::begin_panic::<&str>` at rustc_src/src/panicking.rs:LL:CC
note: inside `<Foo as std::ops::Drop>::drop` at rustc_src/src/panic.rs:LL:CC
  --> $DIR/double_panic.rs:LL:CC
   |
LL |         panic!("second");
   |         ^^^^^^^^^^^^^^^^
   = note: inside `std::ptr::drop_in_place::<Foo> - shim(Some(Foo))` at rustc_src/src/ptr/mod.rs:LL:CC
note: inside `main` at $DIR/double_panic.rs:LL:CC
  --> $DIR/double_panic.rs:LL:CC
   |
LL | }
   | ^
   = note: this error originates in the macro `$crate::panic::panic_2015` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

